services:
  mc:
    image: docker.io/itzg/minecraft-server:latest
    container_name: mc-fabric-server
    stop_grace_period: 2m
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21.1"
      FABRIC_LOADER_VERSION: "0.19.2"
      MEMORY: "6G"
      USE_AIKAR_FLAGS: "TRUE"
      VIEW_DISTANCE: "10"
      SIMULATION_DISTANCE: "8"
      TZ: "Asia/Shanghai"
      ENABLE_WHITELIST: "TRUE"
      ONLINE_MODE: "FALSE"
    volumes:
      - ./data:/data:Z
