# Run 'testparm' to verify the config is correct after
# you modified it.
#
# Note:
# SMB1 is disabled by default. This means clients without support for SMB2 or
# SMB3 are no longer able to connect to smbd (by default).

[global]
    workgroup = WORKGROUP
    security = user
    passdb backend = tdbsam

    load printers = no
    printing = bsd
    printcap name = /dev/null

    browseable = yes
    writable = yes
    guest ok = no
    valid users = ywpc
    force user = ywpc
    acl allow execute always = yes

[New-1]
    comment = New-1 XFS Disk
    path = /mnt/New-1

[New-2]
    comment = New-2 XFS Disk
    path = /mnt/New-2

[Old-1]
    comment = Old-1 XFS Disk
    path = /mnt/Old-1

[Old-2]
    comment = Old-2 XFS Disk
    path = /mnt/Old-2

[Vault-1]
    comment = VeraCrypt Volume
    path = /mnt/Vault-1

[Vault-2]
    comment = VeraCrypt Volume
    path = /mnt/Vault-2

[Temp]
    comment = Temp
    path = /mnt/Temp

[SSD-Cache]
    comment = SSD-Cache
    path = /mnt/SSD-Cache
