services:
  webtop:
    image: localhost/ubuntu-xfce-webtop:v1
    container_name: ubuntu-xfce-webtop
    restart: unless-stopped

    ports:
      - "3000:3000"
      - "3001:3001"
      - "1145:1145"

    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Asia/Shanghai"
      TITLE: "Ubuntu XFCE Webtop"
      CUSTOM_USER: "admin"
      PASSWORD: "<REDACTED-填实际VNC密码>"
      VNC_RESOLUTION: "1600x900"

    volumes:
      - ./config:/config:nosuid,nodev
      - /mnt/New-1:/mnt/New-1:rw,rslave,nosuid,nodev
      - /mnt/New-2:/mnt/New-2:rw,rslave,nosuid,nodev
      - /mnt/Old-1:/mnt/Old-1:rw,rslave,nosuid,nodev
      - /mnt/Old-2:/mnt/Old-2:rw,rslave,nosuid,nodev

    security_opt:
      - label=disable

    devices:
      - /dev/dri:/dev/dri

    group_add:
      - keep-groups

    shm_size: "2g"
